
package Jframe;

import java.util.List;

import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import DAO.goods_DAO;
import DAO.kehu_DAO;
import PO.Goods;
import PO.kehu;
import java.awt.Color;

/**
 *
 * @author  __USER__
 */
public class spxxcx extends JInternalFrame {
	DefaultTableModel model = null;
	/** Creates new form GoodsFrame */
	public spxxcx() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel1.setBackground(Color.ORANGE);
		jPanel1.setForeground(Color.ORANGE);
		jLabel1 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();
		jLabel2 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jComboBox2 = new javax.swing.JComboBox();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jPanel2.setBackground(Color.ORANGE);
		jPanel2.setForeground(Color.ORANGE);
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("\u9009\u62e9\u67e5\u8be2\u65b9\u5f0f");

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"商品名称", "供应商名" }));
		
		jLabel2.setText("\u8f93\u5165\u67e5\u8be2\u5185\u5bb9");

		

		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"包含", "等于" }));

		jButton1.setText("\u67e5\u8be2");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("\u663e\u793a\u5168\u90e8\u4fe1\u606f");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout gl_jPanel1 = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(gl_jPanel1);
		gl_jPanel1
				.setHorizontalGroup(gl_jPanel1
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								gl_jPanel1
										.createSequentialGroup()
										.addGroup(
												gl_jPanel1
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																gl_jPanel1
																		.createSequentialGroup()
																		.addComponent(
																				jLabel2)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				jTextField1,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				226,
																				Short.MAX_VALUE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																gl_jPanel1
																		.createSequentialGroup()
																		.addComponent(
																				jLabel1)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jComboBox1,
																				0,
																				127,
																				Short.MAX_VALUE)
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				jComboBox2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				90,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(102, 102, 102)
										.addGroup(
												gl_jPanel1
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jButton2)
														.addComponent(
																jButton1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																75,
																javax.swing.GroupLayout.PREFERRED_SIZE))));
		gl_jPanel1
				.setVerticalGroup(gl_jPanel1
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								gl_jPanel1
										.createSequentialGroup()
										.addGroup(
												gl_jPanel1
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(jButton2)
														.addComponent(
																jComboBox2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jComboBox1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGroup(
												gl_jPanel1
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton1)
														.addComponent(
																jLabel2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																33,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap()));

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null } },
				new String[] { "商品名", "商品产地", "单位", "规格", "包装", "批准文号",
						"供应商全称", "备注" }));
		jScrollPane1.setViewportView(jTable1);

		javax.swing.GroupLayout gl_jPanel2 = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(gl_jPanel2);
		gl_jPanel2.setHorizontalGroup(gl_jPanel2.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556,
				Short.MAX_VALUE));
		gl_jPanel2.setVerticalGroup(gl_jPanel2.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229,
				Short.MAX_VALUE));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(
														jPanel2,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														jPanel1,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										75,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanel2,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		pack();
		setDefaultCloseOperation(DISPOSE_ON_CLOSE); 
		this.setTitle("商品信息查询");
		setDefaultCloseOperation(DISPOSE_ON_CLOSE); 
		this.setBounds(10,93,1300,450);
		setIconifiable(true);
		setClosable(true);
		setMaximizable(true);
		this.setVisible(true);
	}// </editor-fold>
	//GEN-END:initComponents
	/*
	 * 显示所有信息事件
	 */
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		String[] title = { "商品名", "商品产地", "单位", "规格", "包装", "批准文号", "供应商全称",
			"备注" };
		model = new DefaultTableModel(title, 0);
		goods_DAO list = new goods_DAO();

		try {
				List<Goods> uList = list.getAllGoodsInfo();
				for (Goods info : uList) {
				Object[] o = { info.getGoods_Name(), info.getGoods_Address(),
								info.getGoods_DW(), info.getGoos_gg(),
								info.getGoos_BAZ(), info.getGoos_PH(),
								info.getGoos_GYSName(), info.getGoos_BZ() };
				model.addRow(o);
				}
			} catch (Exception e) {
					e.printStackTrace();
			}
		jTable1.setModel(model);
		}
	/*
	 * 查询事件
	 */
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		String choise1;
		String Text_value;
		String choise2;
		goods_DAO dao = new goods_DAO();
		choise1 = jComboBox1.getSelectedItem().toString();
		choise2 = jComboBox2.getSelectedItem().toString();
		Text_value = jTextField1.getText();
		String sql1 = "select * from goods_info where spmc='" + Text_value+ "'";
		String sql2 = "select * from goods_info where spmc like '%"+ Text_value + "%'";
		String sql3= "select * from goods_info where gysqc='" + Text_value+ "'";
		String sql4 = "select * from goods_info where gysqc like '%"+ Text_value + "%'";
		if (!Text_value.isEmpty()) {
			if (choise1.equals("商品名称")) {
				if (choise2.equals("包含")) {
					List<Goods> list= dao.getGoodsByName(sql2);
					String[] title = { "商品名", "商品产地", "单位", "规格", "包装", "批准文号",
							"供应商全称", "备注" };
					model = new DefaultTableModel(title, 0);

					try {
						for(Goods goods:list){
						Object[] o = { goods.getGoods_Name(), goods.getGoods_Address(),
								goods.getGoods_DW(), goods.getGoos_gg(),
								goods.getGoos_BAZ(), goods.getGoos_PH(),
								goods.getGoos_GYSName(), goods.getGoos_BZ()  };
						model.addRow(o);
						}
					} catch (Exception e) {
						e.printStackTrace();
					}
					jTable1.setModel(model);
				 }
				 if (choise2.equals("等于") ){
					List<Goods> list= dao.getGoodsByName(sql1);
					String[] title = { "商品名", "商品产地", "单位", "规格", "包装", "批准文号",
							"供应商全称", "备注" };
					model = new DefaultTableModel(title, 0);

					try {
						for(Goods goods:list){
						Object[] o = { goods.getGoods_Name(), goods.getGoods_Address(),
								goods.getGoods_DW(), goods.getGoos_gg(),
								goods.getGoos_BAZ(), goods.getGoos_PH(),
								goods.getGoos_GYSName(), goods.getGoos_BZ()  };
						model.addRow(o);
						}
					} catch (Exception e) {
						e.printStackTrace();
					}
					jTable1.setModel(model);
				}
			}if(choise1.equals("供应商名")){
				if (choise2.equals("包含")) {
					List<Goods> list = dao.getGoodsByAddress(sql4);
					String[] title = { "商品名", "商品产地", "单位", "规格", "包装", "批准文号",
							"供应商全称", "备注" };
					model = new DefaultTableModel(title, 0);

					try {
						for(Goods goods:list){
						Object[] o = { goods.getGoods_Name(), goods.getGoods_Address(),
								goods.getGoods_DW(), goods.getGoos_gg(),
								goods.getGoos_BAZ(), goods.getGoos_PH(),
								goods.getGoos_GYSName(), goods.getGoos_BZ()  };
						model.addRow(o);
						}
					} catch (Exception e) {
						e.printStackTrace();
					}
					jTable1.setModel(model);
				 }
				 if (choise2.equals("等于") ){
					List<Goods> list= dao.getGoodsByAddress(sql3);
					String[] title = { "商品名", "商品产地", "单位", "规格", "包装", "批准文号",
							"供应商全称", "备注" };
					model = new DefaultTableModel(title, 0);

					try {
						for(Goods goods:list){
						Object[] o = { goods.getGoods_Name(), goods.getGoods_Address(),
								goods.getGoods_DW(), goods.getGoos_gg(),
								goods.getGoos_BAZ(), goods.getGoos_PH(),
								goods.getGoos_GYSName(), goods.getGoos_BZ()  };
						model.addRow(o);
						}
					} catch (Exception e) {
						e.printStackTrace();
					}
					jTable1.setModel(model);
				 }
			}
		}else{
			JOptionPane.showMessageDialog(null, "请输入查询内容");
		}
	}

	

	/**
	 * @param args the command line arguments
	 */
//	public static void main(String args[]) {
//		java.awt.EventQueue.invokeLater(new Runnable() {
//			public void run() {
//				//new spxxcx().setVisible(true);
//				new spxxcx();
//			}
//		});
//	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JComboBox jComboBox2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}