package Jframe;
/*
 * xiaoshou_Frame.java
 *
 * Created on __DATE__, __TIME__
 */


import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


import DAO.xiaoshou_DAO;

import PO.xiaoShou;
import java.awt.Color;

/**
 *
 * @author  __USER__
 */
public class xiaoshouchaxun extends javax.swing.JInternalFrame {
	DefaultTableModel model = null;

	/** Creates new form xiaoshou_Frame */
	public xiaoshouchaxun() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel1.setBackground(Color.ORANGE);
		jLabel1 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();
		jComboBox2 = new javax.swing.JComboBox();
		jButton1 = new javax.swing.JButton();
		jCheckBox1 = new javax.swing.JCheckBox();
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jButton2 = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jPanel2.setBackground(Color.ORANGE);
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("\u9009\u62e9\u67e5\u8be2\u65b9\u5f0f");

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"商品全称", "操作员" }));

		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"包含", "等于" }));

		jButton1.setText("\u663e\u793a\u5168\u90e8\u5185\u5bb9");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jCheckBox1.setText("\u6307\u5b9a\u662f\u5355\u4ef7(\u5143)");

		jTextField1.setBackground(new java.awt.Color(255, 255, 204));
		
		jTextField2.setBackground(new java.awt.Color(255, 255, 204));
		
		jLabel2.setText("\u4ece");

		jLabel3.setText("\u5230");

		jLabel4.setText("\u8f93\u5165\u67e5\u8be2\u5185\u5bb9");

		jTextField3.setBackground(new java.awt.Color(255, 255, 204));
		

		jButton2.setText("\u67e5\u8be2");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout gl_jPanel1 = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(gl_jPanel1);
		gl_jPanel1
				.setHorizontalGroup(gl_jPanel1
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								gl_jPanel1
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												gl_jPanel1
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jButton1)
														.addComponent(
																jCheckBox1))
										.addGroup(
												gl_jPanel1
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																gl_jPanel1
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel1)
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				jComboBox1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(48,
																				48,
																				48)
																		.addComponent(
																				jComboBox2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				72,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																gl_jPanel1
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel2)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jTextField1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				64,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel3)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				gl_jPanel1
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								gl_jPanel1
																										.createSequentialGroup()
																										.addGap(10,
																												10,
																												10)
																										.addComponent(
																												jButton2))
																						.addGroup(
																								gl_jPanel1
																										.createSequentialGroup()
																										.addComponent(
																												jTextField2,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												71,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(18,
																												18,
																												18)
																										.addComponent(
																												jLabel4)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jTextField3,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												149,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))))
										.addGap(122, 122, 122)));
		gl_jPanel1
				.setVerticalGroup(gl_jPanel1
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								gl_jPanel1
										.createSequentialGroup()
										.addGroup(
												gl_jPanel1
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton1)
														.addComponent(
																jComboBox2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jComboBox1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel1))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												gl_jPanel1
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jCheckBox1)
														.addComponent(jLabel2)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel3)
														.addComponent(
																jTextField2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel4)
														.addComponent(
																jTextField3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												9, Short.MAX_VALUE)
										.addComponent(jButton2)
										.addContainerGap()));

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {
						{ null, null, null, null, null, null, null, null, null,
								null, null },
						{ null, null, null, null, null, null, null, null, null,
								null, null },
						{ null, null, null, null, null, null, null, null, null,
								null, null },
						{ null, null, null, null, null, null, null, null, null,
								null, null } }, new String[] { "销售票号", "商品编号",
						"商品名称", "规格", "单价", "数量", "金额", "客户全称", "销售日期", "操作员",
						"经手人" }));
		jScrollPane1.setViewportView(jTable1);

		javax.swing.GroupLayout gl_jPanel2 = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(gl_jPanel2);
		gl_jPanel2.setHorizontalGroup(gl_jPanel2.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 714,
				Short.MAX_VALUE));
		gl_jPanel2.setVerticalGroup(gl_jPanel2.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				gl_jPanel2
						.createSequentialGroup()
						.addContainerGap()
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 214,
								Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
						714, Short.MAX_VALUE)
				.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanel2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)));

		pack();
		this.setTitle("销售查询");
		setDefaultCloseOperation(DISPOSE_ON_CLOSE); 
		this.setBounds(10,93,1300,450);
		setIconifiable(true);
		setClosable(true);
		setMaximizable(true);
		this.setVisible(true);
	}// </editor-fold>
	//GEN-END:initComponents

	

	/*
	 * 查询事件处理
	 */
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		String choise1 = jComboBox1.getSelectedItem().toString();//第一个下拉框里的字符串
		String choise2 = jComboBox2.getSelectedItem().toString();//第二个下拉框里德字符串
		boolean flag = jCheckBox1.isSelected();//chexbox是否被选中
		String text1 = jTextField1.getText();//第一个文本框（最低价格）的内容
		String text2 = jTextField2.getText();//第二个文本框（最高价格）的内容
		String text3 = jTextField3.getText();//第三个文本框输入查询内容
		String sql="select * from xiaoshou_info where ";
		xiaoshou_DAO dao=new xiaoshou_DAO();
		if(("".equals(text3)&&"".equals(text1)&&"".equals(text2)&&flag)||("".equals(text3)&&!flag)){
			JOptionPane.showMessageDialog(null, "请输入查询内容");
		}else{
			/**
			 * check选中，而查询输入框为空的时候
			 */
			//如果第一个日期文本框不为空而第二个为空，查询内容输入框也为空
			if(!"".equals(text1)&&"".equals(text2)&&"".equals(text3)&&flag){
				List<xiaoShou> list=dao.getInfoBySQL(sql+"piece>'"+text1+"'");
				String[] title = { "销售票号", "商品编号","商品名称", "规格", "单价", 
						"数量", "金额", "客户全称", "销售日期", "操作员","经手人" };
				model = new DefaultTableModel(title, 0);
				for(xiaoShou info:list){
					Object[] o = { info.getXhph(), info.getXhbh(), info.getSpmc(),
							info.getGg(), info.getPiece(), info.getNum(),
							info.getJe(), info.getKhqc(), info.getXsdate(),
							info.getCzy(), info.getJsr()};
					model.addRow(o);
					jTable1.setModel(model);
				}
			}
			//第一个和第三个TEXTfield为空。第二个不为空
			if(!"".equals(text2)&&"".equals(text1)&&"".equals(text3)&&flag){
				List<xiaoShou> list=dao.getInfoBySQL(sql+"piece<"+text2);
				String[] title = { "销售票号", "商品编号","商品名称", "规格", "单价", 
						"数量", "金额", "客户全称", "销售日期", "操作员","经手人" };
				model = new DefaultTableModel(title, 0);
				for(xiaoShou info:list){
					Object[] o = { info.getXhph(), info.getXhbh(), info.getSpmc(),
							info.getGg(), info.getPiece(), info.getNum(),
							info.getJe(), info.getKhqc(), info.getXsdate(),
							info.getCzy(), info.getJsr()};
					model.addRow(o);
					jTable1.setModel(model);
				}	
			}
			//第一个日期文本框的内容不为空，第二个不为空，查询内容输入框也为空
			if(!"".equals(text1)&&!"".equals(text2)&&"".equals(text3)&&flag){
				List<xiaoShou> list=dao.getInfoBySQL(sql+"piece>"+text1+"and piece<"+text2);
				String[] title = { "销售票号", "商品编号","商品名称", "规格", "单价", 
						"数量", "金额", "客户全称", "销售日期", "操作员","经手人" };
				model = new DefaultTableModel(title, 0);
				for(xiaoShou info:list){
					Object[] o = { info.getXhph(), info.getXhbh(), info.getSpmc(),
							info.getGg(), info.getPiece(), info.getNum(),
							info.getJe(), info.getKhqc(), info.getXsdate(),
							info.getCzy(), info.getJsr()};
					model.addRow(o);
					jTable1.setModel(model);
				}
			}
			/**
			 * 对下拉框的选择的不同的操作结果
			 */
			if(choise1.equals("商品全称")){
				if(choise2.equals("等于")){
					if(!flag||(flag&&"".equals(text2)&&"".equals(text1))){
						//checkbos未选中时
						List<xiaoShou> list=dao.getInfoBySQL(sql+"spmc='"+text3+"'");
						String[] title = { "销售票号", "商品编号","商品名称", "规格", "单价", 
								"数量", "金额", "客户全称", "销售日期", "操作员","经手人" };
						model = new DefaultTableModel(title, 0);
						for(xiaoShou info:list){
							Object[] o = { info.getXhph(), info.getXhbh(), info.getSpmc(),
									info.getGg(), info.getPiece(), info.getNum(),
									info.getJe(), info.getKhqc(), info.getXsdate(),
									info.getCzy(), info.getJsr()

							};
							model.addRow(o);
							jTable1.setModel(model);
						}
					}
					if(flag){
						
						//第一个文本框不为空,第二个为空，第三个不为空
						if(!"".equals(text1)&&"".equals(text2)&&!"".equals(text3)){
							List<xiaoShou> list=dao.getInfoBySQL(sql+"piece>"+text1+"and spmc='"+text3+"'");
							String[] title = { "销售票号", "商品编号","商品名称", "规格", "单价", 
									"数量", "金额", "客户全称", "销售日期", "操作员","经手人" };
							model = new DefaultTableModel(title, 0);
							for(xiaoShou info:list){
								Object[] o = { info.getXhph(), info.getXhbh(), info.getSpmc(),
										info.getGg(), info.getPiece(), info.getNum(),
										info.getJe(), info.getKhqc(), info.getXsdate(),
										info.getCzy(), info.getJsr()};
								model.addRow(o);
								jTable1.setModel(model);
							}
						}
						//第一个文本框为空，第二个和第三个不为空
						if("".equals(text1)&&!"".equals(text2)&&!"".equals(text3)){
							List<xiaoShou> list=dao.getInfoBySQL(sql+"piece<"+text2+"and spmc='"+text3+"'");
							String[] title = { "销售票号", "商品编号","商品名称", "规格", "单价", 
									"数量", "金额", "客户全称", "销售日期", "操作员","经手人" };
							model = new DefaultTableModel(title, 0);
							for(xiaoShou info:list){
								Object[] o = { info.getXhph(), info.getXhbh(), info.getSpmc(),
										info.getGg(), info.getPiece(), info.getNum(),
										info.getJe(), info.getKhqc(), info.getXsdate(),
										info.getCzy(), info.getJsr()};
								model.addRow(o);
								jTable1.setModel(model);
							}
						}
						//文本框读不为空
						if(!"".equals(text1)&&!"".equals(text2)&&!"".equals(text3)){
							List<xiaoShou> list=dao.getInfoBySQL(sql+"piece>"+text1+"and piece<"+text2+"and spmc='"+text3+"'");
							String[] title = { "销售票号", "商品编号","商品名称", "规格", "单价", 
									"数量", "金额", "客户全称", "销售日期", "操作员","经手人" };
							model = new DefaultTableModel(title, 0);
							for(xiaoShou info:list){
								Object[] o = { info.getXhph(), info.getXhbh(), info.getSpmc(),
										info.getGg(), info.getPiece(), info.getNum(),
										info.getJe(), info.getKhqc(), info.getXsdate(),
										info.getCzy(), info.getJsr()};
								model.addRow(o);
								jTable1.setModel(model);
							}
						}
					}
						
				}
				if(choise2.equals("包含")){
					
					if(flag&&(!"".equals(text1)||!"".equals(text2))){
						JOptionPane.showMessageDialog(null, "在查询方式为包含时，对单价限定无效");
					}
					List<xiaoShou> list=dao.getInfoBySQL(sql+"spmc like '%"+text3+"%'");
						String[] title = { "销售票号", "商品编号","商品名称", "规格", "单价", 
								"数量", "金额", "客户全称", "销售日期", "操作员","经手人" };
					model = new DefaultTableModel(title, 0);
					for(xiaoShou info:list){
						Object[] o = { info.getXhph(), info.getXhbh(), info.getSpmc(),
									info.getGg(), info.getPiece(), info.getNum(),
									info.getJe(), info.getKhqc(), info.getXsdate(),
									info.getCzy(), info.getJsr()};
						model.addRow(o);
						jTable1.setModel(model);
					}
				}
				
			}
			if(choise1.equals("操作员")){
				if(choise2.equals("等于")){
					if(!flag||(flag&&"".equals(text2)&&"".equals(text1))){
						//checkbos未选中时
						List<xiaoShou> list=dao.getInfoBySQL(sql+"czy='"+text3+"'");
						String[] title = { "销售票号", "商品编号","商品名称", "规格", "单价", 
								"数量", "金额", "客户全称", "销售日期", "操作员","经手人" };
						model = new DefaultTableModel(title, 0);
						for(xiaoShou info:list){
							Object[] o = { info.getXhph(), info.getXhbh(), info.getSpmc(),
									info.getGg(), info.getPiece(), info.getNum(),
									info.getJe(), info.getKhqc(), info.getXsdate(),
									info.getCzy(), info.getJsr()

							};
							model.addRow(o);
							jTable1.setModel(model);
						}
					}
					if(flag){
						//**********
						//第一个文本框不为空,第二个为空，第三个不为空
						if(!"".equals(text1)&&"".equals(text2)&&!"".equals(text3)){
							List<xiaoShou> list=dao.getInfoBySQL(sql+"piece>"+text1+"and czy='"+text3+"'");
							String[] title = { "销售票号", "商品编号","商品名称", "规格", "单价", 
									"数量", "金额", "客户全称", "销售日期", "操作员","经手人" };
							model = new DefaultTableModel(title, 0);
							for(xiaoShou info:list){
								Object[] o = { info.getXhph(), info.getXhbh(), info.getSpmc(),
										info.getGg(), info.getPiece(), info.getNum(),
										info.getJe(), info.getKhqc(), info.getXsdate(),
										info.getCzy(), info.getJsr()};
								model.addRow(o);
								jTable1.setModel(model);
							}
						}
						//第一个文本框为空，第二个和第三个不为空
						if("".equals(text1)&&!"".equals(text2)&&!"".equals(text3)){
							List<xiaoShou> list=dao.getInfoBySQL(sql+"piece<"+text2+"and czy='"+text3+"'");
							String[] title = { "销售票号", "商品编号","商品名称", "规格", "单价", 
									"数量", "金额", "客户全称", "销售日期", "操作员","经手人" };
							model = new DefaultTableModel(title, 0);
							for(xiaoShou info:list){
								Object[] o = { info.getXhph(), info.getXhbh(), info.getSpmc(),
										info.getGg(), info.getPiece(), info.getNum(),
										info.getJe(), info.getKhqc(), info.getXsdate(),
										info.getCzy(), info.getJsr()};
								model.addRow(o);
								jTable1.setModel(model);
							}
						}
						//文本框读不为空
						if(!"".equals(text1)&&!"".equals(text2)&&!"".equals(text3)){
							List<xiaoShou> list=dao.getInfoBySQL(sql+"piece>"+text1+"and piece<"+text2+"and czy='"+text3+"'");
							String[] title = { "销售票号", "商品编号","商品名称", "规格", "单价", 
									"数量", "金额", "客户全称", "销售日期", "操作员","经手人" };
							model = new DefaultTableModel(title, 0);
							for(xiaoShou info:list){
								Object[] o = { info.getXhph(), info.getXhbh(), info.getSpmc(),
										info.getGg(), info.getPiece(), info.getNum(),
										info.getJe(), info.getKhqc(), info.getXsdate(),
										info.getCzy(), info.getJsr()};
								model.addRow(o);
								jTable1.setModel(model);
							}
						}
						//**********
					}
				}
				if(choise2.equals("包含")){
					if(flag&&(!"".equals(text1)||!"".equals(text2))){
						JOptionPane.showMessageDialog(null, "在查询方式为包含时，对单价限定无效");
					}
					List<xiaoShou> list=dao.getInfoBySQL(sql+"czy like '%"+text3+"%'");
						String[] title = { "销售票号", "商品编号","商品名称", "规格", "单价", 
								"数量", "金额", "客户全称", "销售日期", "操作员","经手人" };
					model = new DefaultTableModel(title, 0);
					for(xiaoShou info:list){
						Object[] o = { info.getXhph(), info.getXhbh(), info.getSpmc(),
									info.getGg(), info.getPiece(), info.getNum(),
									info.getJe(), info.getKhqc(), info.getXsdate(),
									info.getCzy(), info.getJsr()};
						model.addRow(o);
						jTable1.setModel(model);
					}
				}
			}
		}
			
		
		
	}

	/*
	 * 显示所有信息
	 */
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		String[] title = { "销售票号", "商品编号", "商品名称", "规格", "单价", "数量", "金额",
				"客户全称", "销售日期", "操作员", "经手人" };
		model = new DefaultTableModel(title, 0);
		xiaoshou_DAO list = new xiaoshou_DAO();

		try {
			List<xiaoShou> uList = list.getAllGYSInfo();
			for (xiaoShou info : uList) {
				Object[] o = { info.getXhph(), info.getXhbh(), info.getSpmc(),
						info.getGg(), info.getPiece(), info.getNum(),
						info.getJe(), info.getKhqc(), info.getXsdate(),
						info.getCzy(), info.getJsr()};
				model.addRow(o);
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		jTable1.setModel(model);
	}

	/**
	 * @param args the command line arguments
	 */
//	public static void main(String args[]) {
//		java.awt.EventQueue.invokeLater(new Runnable() {
//			public void run() {
////				new xiaoshouchaxun().setVisible(true);
//				new xiaoshouchaxun();
//			}
//		});
//	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JComboBox jComboBox2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	// End of variables declaration//GEN-END:variables

}
