package Jframe;
/*
 * salesReturn_view.java
 *
 * Created on __DATE__, __TIME__
 */


import java.util.Date;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import DAO.salesReturn_DAO;
import DAO.xiaoshou_DAO;
import PO.salesReturn;
import PO.xiaoShou;
import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author  __USER__
 */
public class xsthcx extends javax.swing.JInternalFrame {
	DefaultTableModel model = null;

	/** Creates new form salesReturn_view */
	public xsthcx() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel1.setBackground(Color.ORANGE);
		jLabel1 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();
		jButton1 = new javax.swing.JButton();
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jButton2 = new javax.swing.JButton();
		jCheckBox1 = new javax.swing.JCheckBox();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		jPanel2.setBackground(Color.GREEN);
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("\u67e5\u8be2\u65b9\u5f0f\u9009\u62e9");

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"客户全称", "退货票号" }));

		jButton1.setText("\u663e\u793a\u5168\u90e8\u4fe1\u606f");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jTextField1.setText("2000-01-01");
		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});

		jTextField2.setText("2012-12-12");

		jButton2.setText("\u67e5\u8be2");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jCheckBox1.setText("\u5236\u5b9a\u67e5\u8be2\u65e5\u671f");

		jLabel2.setText("\u4ece");

		jLabel3.setText("\u5230");

		jLabel4.setText("\u8f93\u5165\u67e5\u8be2\u5185\u5bb9");

		javax.swing.GroupLayout gl_jPanel1 = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(gl_jPanel1);
		gl_jPanel1
				.setHorizontalGroup(gl_jPanel1
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								gl_jPanel1
										.createSequentialGroup()
										.addGroup(
												gl_jPanel1
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(
																gl_jPanel1
																		.createSequentialGroup()
																		.addGap(3,
																				3,
																				3)
																		.addComponent(
																				jLabel1)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jComboBox1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				jLabel4))
														.addGroup(
																gl_jPanel1
																		.createSequentialGroup()
																		.addComponent(
																				jButton1)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				jCheckBox1)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				jLabel2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				25,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												gl_jPanel1
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																gl_jPanel1
																		.createSequentialGroup()
																		.addComponent(
																				jTextField3,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				180,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton2))
														.addGroup(
																gl_jPanel1
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jTextField1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				101,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel3)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jTextField2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				96,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(222, 222, 222)));
		gl_jPanel1
				.setVerticalGroup(gl_jPanel1
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								gl_jPanel1
										.createSequentialGroup()
										.addGroup(
												gl_jPanel1
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton1)
														.addComponent(
																jCheckBox1)
														.addComponent(jLabel2)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel3)
														.addComponent(
																jTextField2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												gl_jPanel1
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																jComboBox1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel4)
														.addComponent(
																jTextField3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jButton2))
										.addContainerGap()));

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {
						{ null, null, null, null, null, null, null, null, null,
								null, null },
						{ null, null, null, null, null, null, null, null, null,
								null, null },
						{ null, null, null, null, null, null, null, null, null,
								null, null },
						{ null, null, null, null, null, null, null, null, null,
								null, null } }, new String[] { "销售票号", "商品编号",
						"商品名称", "规格", "单价", "退货数量", "操作员", "经手人", "客户全称",
						"结算方式", "总金额" }));
		jScrollPane1.setViewportView(jTable1);

		javax.swing.GroupLayout gl_jPanel2 = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(gl_jPanel2);
		gl_jPanel2.setHorizontalGroup(gl_jPanel2.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 653,
				Short.MAX_VALUE));
		gl_jPanel2.setVerticalGroup(gl_jPanel2.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 383,
				Short.MAX_VALUE));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 653, Short.MAX_VALUE)
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup()
					.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
		);
		getContentPane().setLayout(layout);

		pack();
		this.setTitle("销售退货查询");
		setDefaultCloseOperation(DISPOSE_ON_CLOSE); 
		this.setBounds(10,93,1300,450);
		setIconifiable(true);
		setClosable(true);
		setMaximizable(true);
		this.setVisible(true);
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		boolean flag = jCheckBox1.isSelected();
		String choise = jComboBox1.getSelectedItem().toString();//第一个下拉框里的字符串
		String text1 = jTextField1.getText();
		String text2 = jTextField2.getText();
		String text3 = jTextField3.getText();
		String sql = "select * from tuihuo_table where ";
		salesReturn_DAO dao = new salesReturn_DAO();
		if (("".equals(text3) && !flag)
				|| ("".equals(text3) && "".equals(text1) && "".equals(text2) && flag)) {
			JOptionPane.showMessageDialog(null, "请输入查询内容");
		} else {
			/**
			 * check选中，而查询输入框为空的时候
			 */
			//如果第一个日期文本框不为空而第二个为空，查询内容输入框也为空
			if (!"".equals(text1) && "".equals(text2) && "".equals(text3)
					&& flag) {
				List<salesReturn> list = dao.getReturnBySQL(sql + " THdate>'"
						+ text1 + "'");
				String[] title = { "退货票号", "商品编号", "商品名称", "规格", "单价", "退货数量", "操作员",
						"经手人", "客户全称", "结算方式", "总金额", "退货时间" };
				model = new DefaultTableModel(title, 0);
				for (salesReturn info : list) {
					Object[] o = { info.getThph(), info.getXhbh(),
							info.getSpmc(), info.getGg(), info.getPiece(),
							info.getTnum(), info.getCzy(), info.getJsr(),
							info.getKhqc(), info.getJsfs(), info.getTmoney(),
							info.getTdate() };
					model.addRow(o);
					jTable1.setModel(model);
				}
			}
			//第一个和第三个TEXTfield为空。第二个不为空
			if (!"".equals(text2) && "".equals(text1) && "".equals(text3)
					&& flag) {
				List<salesReturn> list = dao.getReturnBySQL(sql
						+ " THdate<'2012-12-12'");
				String[] title = { "退货票号", "商品编号", "商品名称", "规格", "单价", "退货数量", "操作员",
						"经手人", "客户全称", "结算方式", "总金额", "退货时间"};
				model = new DefaultTableModel(title, 0);
				for (salesReturn info : list) {
					Object[] o = { info.getThph(), info.getXhbh(),
							info.getSpmc(), info.getGg(), info.getPiece(),
							info.getTnum(), info.getCzy(), info.getJsr(),
							info.getKhqc(), info.getJsfs(), info.getTmoney(),
							info.getTdate() };
					model.addRow(o);
					jTable1.setModel(model);
				}
			}
			//第一个日期文本框的内容不为空，第二个不为空，查询内容输入框也为空
			if (!"".equals(text1) && !"".equals(text2) && "".equals(text3)
					&& flag) {
				List<salesReturn> list = dao.getReturnBySQL(sql + " THdate>"
						+ text1 + "and THdate<'" + text2 + "'");
				String[] title = {"退货票号", "商品编号", "商品名称", "规格", "单价", "退货数量", "操作员",
						"经手人", "客户全称", "结算方式", "总金额", "退货时间" };
				model = new DefaultTableModel(title, 0);
				for (salesReturn info : list) {
					Object[] o = { info.getThph(), info.getXhbh(),
							info.getSpmc(), info.getGg(), info.getPiece(),
							info.getTnum(), info.getCzy(), info.getJsr(),
							info.getKhqc(), info.getJsfs(), info.getTmoney(),
							info.getTdate() };
					model.addRow(o);
					jTable1.setModel(model);
				}
			}
			//下拉框选择处理
			if (choise.equals("退货票号")) {
				if (!flag || (flag && "".equals(text2) && "".equals(text1))) {

					List<salesReturn> list = dao.getReturnBySQL(sql + "thph='"
							+ text3 + "'");
					String[] title = { "退货票号", "商品编号", "商品名称", "规格", "单价", "退货数量", "操作员",
							"经手人", "客户全称", "结算方式", "总金额", "退货时间" };
					model = new DefaultTableModel(title, 0);
					for (salesReturn info : list) {
						Object[] o = { info.getThph(), info.getXhbh(),
								info.getSpmc(), info.getGg(), info.getPiece(),
								info.getTnum(), info.getCzy(), info.getJsr(),
								info.getKhqc(), info.getJsfs(),
								info.getTmoney(), info.getTdate() };
						model.addRow(o);
						jTable1.setModel(model);
					}
				}
				if (flag) {
					//第一个文本框不为空,第二个为空，第三个不为空
					if (!"".equals(text1) && "".equals(text2)
							&& !"".equals(text3)) {
						JOptionPane.showMessageDialog(null, "55");
						List<salesReturn> list = dao.getReturnBySQL(sql
								+ "THdate>" + text1 + "and thph='" + text3
								+ "'");
						String[] title = { "退货票号", "商品编号", "商品名称", "规格", "单价", "退货数量", "操作员",
								"经手人", "客户全称", "结算方式", "总金额", "退货时间" };
						model = new DefaultTableModel(title, 0);
						for (salesReturn info : list) {
							Object[] o = { info.getThph(), info.getXhbh(),
									info.getSpmc(), info.getGg(),
									info.getPiece(), info.getTnum(),
									info.getCzy(), info.getJsr(),
									info.getKhqc(), info.getJsfs(),
									info.getTmoney(), info.getTdate() };
							model.addRow(o);
							jTable1.setModel(model);
						}
					}
					//第一个文本框为空，第二个和第三个不为空
					if ("".equals(text1) && !"".equals(text2)
							&& !"".equals(text3)) {
						List<salesReturn> list = dao.getReturnBySQL(sql
								+ "THdate<" + text2 + "and thph='" + text3
								+ "'");
						String[] title = {"退货票号", "商品编号", "商品名称", "规格", "单价", "退货数量", "操作员",
								"经手人", "客户全称", "结算方式", "总金额", "退货时间" };
						model = new DefaultTableModel(title, 0);
						for (salesReturn info : list) {
							Object[] o = { info.getThph(), info.getXhbh(),
									info.getSpmc(), info.getGg(),
									info.getPiece(), info.getTnum(),
									info.getCzy(), info.getJsr(),
									info.getKhqc(), info.getJsfs(),
									info.getTmoney(), info.getTdate() };
							model.addRow(o);
							jTable1.setModel(model);
						}
					}
					//文本框都不为空
					if (!"".equals(text1) && !"".equals(text2)
							&& !"".equals(text3)) {
						List<salesReturn> list = dao.getReturnBySQL(sql
								+ "THdate>" + text1 + "and THdate<" + text2
								+ "and thph='" + text3 + "'");
						String[] title = {"退货票号", "商品编号", "商品名称", "规格", "单价", "退货数量", "操作员",
								"经手人", "客户全称", "结算方式", "总金额", "退货时间"};
						model = new DefaultTableModel(title, 0);
						for (salesReturn info : list) {
							Object[] o = { info.getThph(), info.getXhbh(),
									info.getSpmc(), info.getGg(),
									info.getPiece(), info.getTnum(),
									info.getCzy(), info.getJsr(),
									info.getKhqc(), info.getJsfs(),
									info.getTmoney(), info.getTdate() };
							model.addRow(o);
							jTable1.setModel(model);
						}
					}
				}
				if(!flag&&!"".equals(text3)){
					List<salesReturn> list = dao.getReturnBySQL(sql+ " thph='" + text3 + "'");
					String[] title = {"退货票号", "商品编号", "商品名称", "规格", "单价", "退货数量", "操作员",
							"经手人", "客户全称", "结算方式", "总金额", "退货时间"};
					model = new DefaultTableModel(title, 0);
					for (salesReturn info : list) {
						Object[] o = { info.getThph(), info.getXhbh(),
								info.getSpmc(), info.getGg(),
								info.getPiece(), info.getTnum(),
								info.getCzy(), info.getJsr(),
								info.getKhqc(), info.getJsfs(),
								info.getTmoney(), info.getTdate() };
						model.addRow(o);
						jTable1.setModel(model);
					}
				}
			}
			if (choise.equals("客户全称")) {
				//第一个文本框不为空,第二个为空，第三个不为空
				if (!"".equals(text1) && "".equals(text2)
						&& !"".equals(text3)) {
					JOptionPane.showMessageDialog(null, "55");
					List<salesReturn> list = dao.getReturnBySQL(sql
							+ "THdate>" + text1 + "and khqc='" + text3
							+ "'");
					String[] title = { "退货票号", "商品编号", "商品名称", "规格", "单价", "退货数量", "操作员",
							"经手人", "客户全称", "结算方式", "总金额", "退货时间" };
					model = new DefaultTableModel(title, 0);
					for (salesReturn info : list) {
						Object[] o = { info.getThph(), info.getXhbh(),
								info.getSpmc(), info.getGg(),
								info.getPiece(), info.getTnum(),
								info.getCzy(), info.getJsr(),
								info.getKhqc(), info.getJsfs(),
								info.getTmoney(), info.getTdate() };
						model.addRow(o);
						jTable1.setModel(model);
					}
				}
				//第一个文本框为空，第二个和第三个不为空
				if ("".equals(text1) && !"".equals(text2)
						&& !"".equals(text3)) {
					List<salesReturn> list = dao.getReturnBySQL(sql
							+ "THdate<" + text2 + "and khqc='" + text3
							+ "'");
					String[] title = {"退货票号", "商品编号", "商品名称", "规格", "单价", "退货数量", "操作员",
							"经手人", "客户全称", "结算方式", "总金额", "退货时间" };
					model = new DefaultTableModel(title, 0);
					for (salesReturn info : list) {
						Object[] o = { info.getThph(), info.getXhbh(),
								info.getSpmc(), info.getGg(),
								info.getPiece(), info.getTnum(),
								info.getCzy(), info.getJsr(),
								info.getKhqc(), info.getJsfs(),
								info.getTmoney(), info.getTdate() };
						model.addRow(o);
						jTable1.setModel(model);
					}
				}
				//文本框都不为空
				if (!"".equals(text1) && !"".equals(text2)
						&& !"".equals(text3)) {
					List<salesReturn> list = dao.getReturnBySQL(sql
							+ "THdate>" + text1 + "and THdate<" + text2
							+ "and khqc='" + text3 + "'");
					String[] title = {"退货票号", "商品编号", "商品名称", "规格", "单价", "退货数量", "操作员",
							"经手人", "客户全称", "结算方式", "总金额", "退货时间"};
					model = new DefaultTableModel(title, 0);
					for (salesReturn info : list) {
						Object[] o = { info.getThph(), info.getXhbh(),
								info.getSpmc(), info.getGg(),
								info.getPiece(), info.getTnum(),
								info.getCzy(), info.getJsr(),
								info.getKhqc(), info.getJsfs(),
								info.getTmoney(), info.getTdate() };
						model.addRow(o);
						jTable1.setModel(model);
					}
				}
			}
			//check未选中，JTextfield不为空
			if(!flag&&!"".equals(text3)){
				List<salesReturn> list = dao.getReturnBySQL(sql+ " khqc='" + text3 + "'");
				String[] title = {"退货票号", "商品编号", "商品名称", "规格", "单价", "退货数量", "操作员",
						"经手人", "客户全称", "结算方式", "总金额", "退货时间"};
				model = new DefaultTableModel(title, 0);
				for (salesReturn info : list) {
					Object[] o = { info.getThph(), info.getXhbh(),
							info.getSpmc(), info.getGg(),
							info.getPiece(), info.getTnum(),
							info.getCzy(), info.getJsr(),
							info.getKhqc(), info.getJsfs(),
							info.getTmoney(), info.getTdate() };
					model.addRow(o);
					jTable1.setModel(model);
				}
			}
			
		}

	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		String[] title = { "退货票号", "商品编号", "商品名称", "规格", "单价", "退货数量", "操作员",
				"经手人", "客户全称", "结算方式", "总金额", "退货时间" };
		model = new DefaultTableModel(title, 0);
		salesReturn_DAO list = new salesReturn_DAO();

		try {
			List<salesReturn> uList = list.getAllReturn();
			for (salesReturn info : uList) {
				Object[] o = { info.getThph(), info.getXhbh(), info.getSpmc(),
						info.getGg(), info.getPiece(), info.getTnum(),
						info.getCzy(), info.getJsr(), info.getKhqc(),
						info.getJsfs(), info.getTmoney(), info.getTdate() };
				model.addRow(o);
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		jTable1.setModel(model);
	}

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
//	public static void main(String args[]) {
//		java.awt.EventQueue.invokeLater(new Runnable() {
//			public void run() {
////				new xsthcx().setVisible(true);
//				new xsthcx();
//			}
//		});
//	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	// End of variables declaration//GEN-END:variables

}
